name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Replace with the specific Python version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run unit tests
      - name: Run tests
        run: |
          pytest tests/ --junitxml=test-results.xml
        continue-on-error: false

      # Step 5: Upload test results (optional)
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml
